package com.emailForemsic.emailForensic.entity;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "email_cases")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class EmailCase {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String fileName;

    private String fileHash;

    private String analysisStatus;

    private Integer threatScore;

    private String originatingIp;

    @Column(columnDefinition = "TEXT")
    private String receivedHeaders;

    /**
     * Parsed email body.
     *
     * This is also used as the source text sent to the AI analysis service.
     */
    @Column(columnDefinition = "TEXT")
    private String rawBody;

    private String spoofingRisk;

    @Column(columnDefinition = "TEXT")
    private String spoofingFindings;


    // -----------------------------------------------------------------------
    // Approximate IP geolocation
    // -----------------------------------------------------------------------

    private String geoCountry;

    private String geoCity;

    private Double geoLatitude;

    private Double geoLongitude;

    private String geoTimezone;


    // -----------------------------------------------------------------------
    // Sender IP Intelligence
    // -----------------------------------------------------------------------

    /**
     * Sender/client IP from explicit client-origin headers only.
     *
     * Examples:
     * X-Originating-IP
     * X-Sender-IP
     * X-Client-IP
     * X-Real-IP
     * Received-SPF client-ip
     */
    private String senderIp;

    /**
     * Header/source that provided senderIp.
     */
    private String senderIpSource;

    /**
     * Confidence classification for senderIp.
     */
    private String senderIpConfidence;


    // -----------------------------------------------------------------------
    // Connecting IP Intelligence
    // -----------------------------------------------------------------------

    /**
     * Connecting IP observed by the receiving MTA.
     *
     * This may be a mail relay/infrastructure IP and should not be
     * confused with senderIp.
     */
    private String connectingIp;

    private String connectingIpSource;

    private String connectingIpConfidence;


    // -----------------------------------------------------------------------
    // AI FORENSIC ANALYSIS
    //
    // Spring Boot
    //      ↓
    // Python FastAPI
    //      ↓
    // CISA RAG
    //      ↓
    // Llama
    //      ↓
    // Structured forensic result
    // -----------------------------------------------------------------------

    /**
     * AI-generated risk level.
     *
     * Example:
     * LOW_RISK
     * MEDIUM_RISK
     * HIGH_RISK
     * CRITICAL_RISK
     */
    private String aiRiskLevel;

    /**
     * AI-generated verdict.
     *
     * Example:
     * LEGITIMATE
     * SUSPICIOUS
     * MALICIOUS
     * PHISHING
     */
    private String aiVerdict;

    /**
     * AI confidence percentage.
     */
    private Double aiConfidence;

    /**
     * AI-generated forensic summary.
     */
    @Column(columnDefinition = "TEXT")
    private String aiSummary;

    /**
     * AI reasoning/evidence chain stored as JSON.
     */
    @Column(columnDefinition = "TEXT")
    private String aiReasoning;

    /**
     * AI-detected indicators stored as JSON.
     */
    @Column(columnDefinition = "TEXT")
    private String aiIndicators;

    /**
     * ATT&CK / attack techniques identified by AI.
     */
    @Column(columnDefinition = "TEXT")
    private String aiAttackTechniques;

    /**
     * Extracted indicators of compromise.
     *
     * Stored as JSON because the Python service returns a structured map.
     */
    @Column(columnDefinition = "TEXT")
    private String aiIocs;

    /**
     * AI analysis of the email's origin.
     */
    @Column(columnDefinition = "TEXT")
    private String aiOriginAnalysis;

    /**
     * CISA/RAG information used during analysis.
     */
    @Column(columnDefinition = "TEXT")
    private String aiRagInsights;

    /**
     * Domain/WHOIS/RDAP-style intelligence returned by AI service.
     */
    @Column(columnDefinition = "TEXT")
    private String aiWhoisAnalysis;

    /**
     * URL analysis returned by AI service.
     */
    @Column(columnDefinition = "TEXT")
    private String aiUrlAnalysis;

    /**
     * Graph/network relationship data generated by AI analysis.
     */
    @Column(columnDefinition = "TEXT")
    private String aiGraphs;

    /**
     * AI service error, if AI analysis failed.
     *
     * Email ingestion itself should still be able to succeed when
     * the AI service is unavailable.
     */
    @Column(columnDefinition = "TEXT")
    private String aiError;


    // -----------------------------------------------------------------------
    // TIMESTAMP
    // -----------------------------------------------------------------------

    private LocalDateTime createdAt;


    // -----------------------------------------------------------------------
    // RELATIONSHIPS
    // -----------------------------------------------------------------------

    @JsonManagedReference
    @OneToOne(
            mappedBy = "emailCase",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private EmailHeader header;


    @JsonManagedReference
    @Builder.Default
    @OneToMany(
            mappedBy = "emailCase",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<EmailIndicator> indicators = new ArrayList<>();


    // -----------------------------------------------------------------------
    // HELPER METHODS
    // -----------------------------------------------------------------------

    public void setHeader(EmailHeader header) {

        this.header = header;

        if (header != null) {
            header.setEmailCase(this);
        }
    }


    public void addIndicator(EmailIndicator indicator) {

        if (this.indicators == null) {
            this.indicators = new ArrayList<>();
        }

        this.indicators.add(indicator);

        if (indicator != null) {
            indicator.setEmailCase(this);
        }
    }
}